export const defaultResults = {
  results: [
    {
      gender: 'female',
      name: { title: 'Mrs', first: 'Asta', last: 'Nielsen' },
      email: 'asta.nielsen@example.com',
      phone: '21796233',
      picture: {
        large: 'https://randomuser.me/api/portraits/women/42.jpg',
        medium: 'https://randomuser.me/api/portraits/med/women/42.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/women/42.jpg',
      },
    },
    {
      gender: 'male',
      name: { title: 'Mr', first: 'Michael', last: 'Williams' },
      email: 'michael.williams@example.com',
      phone: '(915)-658-0146',
      picture: {
        large: 'https://randomuser.me/api/portraits/men/66.jpg',
        medium: 'https://randomuser.me/api/portraits/med/men/66.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/men/66.jpg',
      },
    },
    {
      gender: 'female',
      name: { title: 'Miss', first: 'Ella', last: 'Suprun' },
      email: 'ella.suprun@example.com',
      phone: '(096) V87-2998',
      picture: {
        large: 'https://randomuser.me/api/portraits/women/87.jpg',
        medium: 'https://randomuser.me/api/portraits/med/women/87.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/women/87.jpg',
      },
    },
    {
      gender: 'male',
      name: { title: 'Mr', first: 'Ramon', last: 'Arias' },
      email: 'ramon.arias@example.com',
      phone: '999-503-881',
      picture: {
        large: 'https://randomuser.me/api/portraits/men/39.jpg',
        medium: 'https://randomuser.me/api/portraits/med/men/39.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/men/39.jpg',
      },
    },
    {
      gender: 'female',
      name: { title: 'Ms', first: 'Maja', last: 'Rasmussen' },
      email: 'maja.rasmussen@example.com',
      phone: '32208226',
      picture: {
        large: 'https://randomuser.me/api/portraits/women/61.jpg',
        medium: 'https://randomuser.me/api/portraits/med/women/61.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/women/61.jpg',
      },
    },
    {
      gender: 'male',
      name: { title: 'Mr', first: 'Mikkel', last: 'Christiansen' },
      email: 'mikkel.christiansen@example.com',
      phone: '30171633',
      picture: {
        large: 'https://randomuser.me/api/portraits/men/19.jpg',
        medium: 'https://randomuser.me/api/portraits/med/men/19.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/men/19.jpg',
      },
    },
    {
      gender: 'female',
      name: { title: 'Ms', first: 'Janet', last: 'Cooper' },
      email: 'janet.cooper@example.com',
      phone: '015394 16467',
      picture: {
        large: 'https://randomuser.me/api/portraits/women/26.jpg',
        medium: 'https://randomuser.me/api/portraits/med/women/26.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/women/26.jpg',
      },
    },
    {
      gender: 'male',
      name: { title: 'Mr', first: 'Vitomir', last: 'Trajković' },
      email: 'vitomir.trajkovic@example.com',
      phone: '013-6232-484',
      picture: {
        large: 'https://randomuser.me/api/portraits/men/27.jpg',
        medium: 'https://randomuser.me/api/portraits/med/men/27.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/men/27.jpg',
      },
    },
    {
      gender: 'female',
      name: { title: 'Miss', first: 'Carol', last: 'Rhodes' },
      email: 'carol.rhodes@example.com',
      phone: '011-584-8769',
      picture: {
        large: 'https://randomuser.me/api/portraits/women/52.jpg',
        medium: 'https://randomuser.me/api/portraits/med/women/52.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/women/52.jpg',
      },
    },
    {
      gender: 'female',
      name: { title: 'Mrs', first: 'Berta', last: 'Parra' },
      email: 'berta.parra@example.com',
      phone: '(694) 546 3118',
      picture: {
        large: 'https://randomuser.me/api/portraits/women/96.jpg',
        medium: 'https://randomuser.me/api/portraits/med/women/96.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/women/96.jpg',
      },
    },
    {
      gender: 'male',
      name: { title: 'Mr', first: 'احسان', last: 'قاسمی' },
      email: 'hsn.qsmy@example.com',
      phone: '005-86193000',
      picture: {
        large: 'https://randomuser.me/api/portraits/men/22.jpg',
        medium: 'https://randomuser.me/api/portraits/med/men/22.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/men/22.jpg',
      },
    },
    {
      gender: 'female',
      name: { title: 'Miss', first: 'Flavie', last: 'Faure' },
      email: 'flavie.faure@example.com',
      phone: '04-62-55-77-48',
      picture: {
        large: 'https://randomuser.me/api/portraits/women/72.jpg',
        medium: 'https://randomuser.me/api/portraits/med/women/72.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/women/72.jpg',
      },
    },
    {
      gender: 'male',
      name: { title: 'Mr', first: 'Sigurd', last: 'Skinstad' },
      email: 'sigurd.skinstad@example.com',
      phone: '30418470',
      picture: {
        large: 'https://randomuser.me/api/portraits/men/19.jpg',
        medium: 'https://randomuser.me/api/portraits/med/men/19.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/men/19.jpg',
      },
    },
    {
      gender: 'female',
      name: { title: 'Miss', first: 'Wally', last: 'Franz' },
      email: 'wally.franz@example.com',
      phone: '0012-1619158',
      picture: {
        large: 'https://randomuser.me/api/portraits/women/47.jpg',
        medium: 'https://randomuser.me/api/portraits/med/women/47.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/women/47.jpg',
      },
    },
    {
      gender: 'female',
      name: { title: 'Ms', first: 'Caroline', last: 'Santos' },
      email: 'caroline.santos@example.com',
      phone: '(50) 4507-7487',
      picture: {
        large: 'https://randomuser.me/api/portraits/women/0.jpg',
        medium: 'https://randomuser.me/api/portraits/med/women/0.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/women/0.jpg',
      },
    },
    {
      gender: 'male',
      name: { title: 'Mr', first: 'Harro', last: 'Gohlke' },
      email: 'harro.gohlke@example.com',
      phone: '0013-1219773',
      picture: {
        large: 'https://randomuser.me/api/portraits/men/54.jpg',
        medium: 'https://randomuser.me/api/portraits/med/men/54.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/men/54.jpg',
      },
    },
    {
      gender: 'female',
      name: { title: 'Mrs', first: 'Akshatha', last: 'Bhoja' },
      email: 'akshatha.bhoja@example.com',
      phone: '7335238428',
      picture: {
        large: 'https://randomuser.me/api/portraits/women/61.jpg',
        medium: 'https://randomuser.me/api/portraits/med/women/61.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/women/61.jpg',
      },
    },
    {
      gender: 'male',
      name: { title: 'Mr', first: 'رضا', last: 'گلشن' },
      email: 'rd.glshn@example.com',
      phone: '078-44468039',
      picture: {
        large: 'https://randomuser.me/api/portraits/men/68.jpg',
        medium: 'https://randomuser.me/api/portraits/med/men/68.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/men/68.jpg',
      },
    },
    {
      gender: 'female',
      name: { title: 'Miss', first: 'Kaitlin', last: 'Carpenter' },
      email: 'kaitlin.carpenter@example.com',
      phone: '011-524-3020',
      picture: {
        large: 'https://randomuser.me/api/portraits/women/53.jpg',
        medium: 'https://randomuser.me/api/portraits/med/women/53.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/women/53.jpg',
      },
    },
    {
      gender: 'male',
      name: { title: 'Mr', first: 'Upkaar', last: 'Bhoja' },
      email: 'upkaar.bhoja@example.com',
      phone: '8966812439',
      picture: {
        large: 'https://randomuser.me/api/portraits/men/65.jpg',
        medium: 'https://randomuser.me/api/portraits/med/men/65.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/men/65.jpg',
      },
    },
    {
      gender: 'male',
      name: { title: 'Mr', first: 'Adem', last: 'Akyürek' },
      email: 'adem.akyurek@example.com',
      phone: '(841)-587-6280',
      picture: {
        large: 'https://randomuser.me/api/portraits/men/51.jpg',
        medium: 'https://randomuser.me/api/portraits/med/men/51.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/men/51.jpg',
      },
    },
    {
      gender: 'male',
      name: { title: 'Mr', first: 'رادین', last: 'علیزاده' },
      email: 'rdyn.aalyzdh@example.com',
      phone: '053-32943941',
      picture: {
        large: 'https://randomuser.me/api/portraits/men/85.jpg',
        medium: 'https://randomuser.me/api/portraits/med/men/85.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/men/85.jpg',
      },
    },
    {
      gender: 'female',
      name: { title: 'Ms', first: 'Chantal', last: 'Hennecke' },
      email: 'chantal.hennecke@example.com',
      phone: '0820-1944762',
      picture: {
        large: 'https://randomuser.me/api/portraits/women/43.jpg',
        medium: 'https://randomuser.me/api/portraits/med/women/43.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/women/43.jpg',
      },
    },
    {
      gender: 'male',
      name: { title: 'Mr', first: 'Darryl', last: 'Carter' },
      email: 'darryl.carter@example.com',
      phone: '09-6049-5842',
      picture: {
        large: 'https://randomuser.me/api/portraits/men/87.jpg',
        medium: 'https://randomuser.me/api/portraits/med/men/87.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/men/87.jpg',
      },
    },
    {
      gender: 'female',
      name: { title: 'Mrs', first: 'Kashvi', last: 'Sheikh' },
      email: 'kashvi.sheikh@example.com',
      phone: '8127427425',
      picture: {
        large: 'https://randomuser.me/api/portraits/women/13.jpg',
        medium: 'https://randomuser.me/api/portraits/med/women/13.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/women/13.jpg',
      },
    },
    {
      gender: 'female',
      name: { title: 'Mrs', first: 'Akhila', last: 'Dalvi' },
      email: 'akhila.dalvi@example.com',
      phone: '9186762245',
      picture: {
        large: 'https://randomuser.me/api/portraits/women/84.jpg',
        medium: 'https://randomuser.me/api/portraits/med/women/84.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/women/84.jpg',
      },
    },
    {
      gender: 'male',
      name: { title: 'Mr', first: 'Ostoja', last: 'Dinčić' },
      email: 'ostoja.dincic@example.com',
      phone: '010-6850-619',
      picture: {
        large: 'https://randomuser.me/api/portraits/men/40.jpg',
        medium: 'https://randomuser.me/api/portraits/med/men/40.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/men/40.jpg',
      },
    },
    {
      gender: 'male',
      name: { title: 'Mr', first: 'میلاد', last: 'نكو نظر' },
      email: 'myld.nkwnzr@example.com',
      phone: '011-14998510',
      picture: {
        large: 'https://randomuser.me/api/portraits/men/22.jpg',
        medium: 'https://randomuser.me/api/portraits/med/men/22.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/men/22.jpg',
      },
    },
    {
      gender: 'male',
      name: { title: 'Mr', first: 'Felix', last: 'Petersen' },
      email: 'felix.petersen@example.com',
      phone: '79669429',
      picture: {
        large: 'https://randomuser.me/api/portraits/men/71.jpg',
        medium: 'https://randomuser.me/api/portraits/med/men/71.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/men/71.jpg',
      },
    },
    {
      gender: 'male',
      name: { title: 'Monsieur', first: 'Ralph', last: 'Garnier' },
      email: 'ralph.garnier@example.com',
      phone: '079 038 16 75',
      picture: {
        large: 'https://randomuser.me/api/portraits/men/66.jpg',
        medium: 'https://randomuser.me/api/portraits/med/men/66.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/men/66.jpg',
      },
    },
    {
      gender: 'female',
      name: { title: 'Ms', first: 'Sonia', last: 'Cortes' },
      email: 'sonia.cortes@example.com',
      phone: '935-739-272',
      picture: {
        large: 'https://randomuser.me/api/portraits/women/35.jpg',
        medium: 'https://randomuser.me/api/portraits/med/women/35.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/women/35.jpg',
      },
    },
    {
      gender: 'female',
      name: { title: 'Ms', first: 'Snežana', last: 'Abramović' },
      email: 'snezana.abramovic@example.com',
      phone: '035-3780-779',
      picture: {
        large: 'https://randomuser.me/api/portraits/women/61.jpg',
        medium: 'https://randomuser.me/api/portraits/med/women/61.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/women/61.jpg',
      },
    },
    {
      gender: 'male',
      name: { title: 'Mr', first: 'Gustavo', last: 'Moreno' },
      email: 'gustavo.moreno@example.com',
      phone: '906-848-523',
      picture: {
        large: 'https://randomuser.me/api/portraits/men/27.jpg',
        medium: 'https://randomuser.me/api/portraits/med/men/27.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/men/27.jpg',
      },
    },
    {
      gender: 'male',
      name: { title: 'Mr', first: 'علی', last: 'صدر' },
      email: 'aaly.sdr@example.com',
      phone: '077-42571587',
      picture: {
        large: 'https://randomuser.me/api/portraits/men/91.jpg',
        medium: 'https://randomuser.me/api/portraits/med/men/91.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/men/91.jpg',
      },
    },
    {
      gender: 'male',
      name: { title: 'Mr', first: 'Nikolaj', last: 'Jørgensen' },
      email: 'nikolaj.jorgensen@example.com',
      phone: '73654879',
      picture: {
        large: 'https://randomuser.me/api/portraits/men/20.jpg',
        medium: 'https://randomuser.me/api/portraits/med/men/20.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/men/20.jpg',
      },
    },
    {
      gender: 'female',
      name: { title: 'Miss', first: 'Caitlin', last: 'Robinson' },
      email: 'caitlin.robinson@example.com',
      phone: '(114)-911-0631',
      picture: {
        large: 'https://randomuser.me/api/portraits/women/0.jpg',
        medium: 'https://randomuser.me/api/portraits/med/women/0.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/women/0.jpg',
      },
    },
    {
      gender: 'male',
      name: { title: 'Mr', first: 'Luka', last: 'Tamm' },
      email: 'luka.tamm@example.com',
      phone: '0932-0688196',
      picture: {
        large: 'https://randomuser.me/api/portraits/men/56.jpg',
        medium: 'https://randomuser.me/api/portraits/med/men/56.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/men/56.jpg',
      },
    },
    {
      gender: 'female',
      name: { title: 'Miss', first: 'Gül', last: 'Sandalcı' },
      email: 'gul.sandalci@example.com',
      phone: '(292)-744-4524',
      picture: {
        large: 'https://randomuser.me/api/portraits/women/66.jpg',
        medium: 'https://randomuser.me/api/portraits/med/women/66.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/women/66.jpg',
      },
    },
    {
      gender: 'male',
      name: { title: 'Mr', first: 'Felix', last: 'Lynch' },
      email: 'felix.lynch@example.com',
      phone: '(389) 575-1080',
      picture: {
        large: 'https://randomuser.me/api/portraits/men/23.jpg',
        medium: 'https://randomuser.me/api/portraits/med/men/23.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/men/23.jpg',
      },
    },
    {
      gender: 'male',
      name: { title: 'Mr', first: 'Pavlo', last: 'Grinchak' },
      email: 'pavlo.grinchak@example.com',
      phone: '(067) F68-7241',
      picture: {
        large: 'https://randomuser.me/api/portraits/men/31.jpg',
        medium: 'https://randomuser.me/api/portraits/med/men/31.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/men/31.jpg',
      },
    },
    {
      gender: 'male',
      name: { title: 'Mr', first: 'Vseslav', last: 'Verhratskiy' },
      email: 'vseslav.verhratskiy@example.com',
      phone: '(067) K34-5458',
      picture: {
        large: 'https://randomuser.me/api/portraits/men/79.jpg',
        medium: 'https://randomuser.me/api/portraits/med/men/79.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/men/79.jpg',
      },
    },
    {
      gender: 'female',
      name: { title: 'Miss', first: 'Danielle', last: 'Jacobs' },
      email: 'danielle.jacobs@example.com',
      phone: '021-476-4771',
      picture: {
        large: 'https://randomuser.me/api/portraits/women/85.jpg',
        medium: 'https://randomuser.me/api/portraits/med/women/85.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/women/85.jpg',
      },
    },
    {
      gender: 'female',
      name: { title: 'Mrs', first: 'Julie', last: 'Rodriguez' },
      email: 'julie.rodriguez@example.com',
      phone: '05-87-37-12-85',
      picture: {
        large: 'https://randomuser.me/api/portraits/women/13.jpg',
        medium: 'https://randomuser.me/api/portraits/med/women/13.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/women/13.jpg',
      },
    },
    {
      gender: 'female',
      name: { title: 'Ms', first: 'Olivia', last: 'Macdonald' },
      email: 'olivia.macdonald@example.com',
      phone: 'Z30 K59-2899',
      picture: {
        large: 'https://randomuser.me/api/portraits/women/92.jpg',
        medium: 'https://randomuser.me/api/portraits/med/women/92.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/women/92.jpg',
      },
    },
    {
      gender: 'male',
      name: { title: 'Mr', first: 'Felix', last: 'Petersen' },
      email: 'felix.petersen@example.com',
      phone: '73627685',
      picture: {
        large: 'https://randomuser.me/api/portraits/men/31.jpg',
        medium: 'https://randomuser.me/api/portraits/med/men/31.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/men/31.jpg',
      },
    },
    {
      gender: 'male',
      name: { title: 'Mr', first: 'Vlatko', last: 'Rodić' },
      email: 'vlatko.rodic@example.com',
      phone: '024-7899-903',
      picture: {
        large: 'https://randomuser.me/api/portraits/men/49.jpg',
        medium: 'https://randomuser.me/api/portraits/med/men/49.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/men/49.jpg',
      },
    },
    {
      gender: 'male',
      name: { title: 'Mr', first: 'Parth', last: 'Shukla' },
      email: 'parth.shukla@example.com',
      phone: '8120617885',
      picture: {
        large: 'https://randomuser.me/api/portraits/men/67.jpg',
        medium: 'https://randomuser.me/api/portraits/med/men/67.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/men/67.jpg',
      },
    },
    {
      gender: 'female',
      name: { title: 'Miss', first: 'Clarice', last: 'Barros' },
      email: 'clarice.barros@example.com',
      phone: '(30) 5687-2227',
      picture: {
        large: 'https://randomuser.me/api/portraits/women/59.jpg',
        medium: 'https://randomuser.me/api/portraits/med/women/59.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/women/59.jpg',
      },
    },
    {
      gender: 'female',
      name: { title: 'Mrs', first: 'Stefanija', last: 'Vujić' },
      email: 'stefanija.vujic@example.com',
      phone: '014-7971-984',
      picture: {
        large: 'https://randomuser.me/api/portraits/women/68.jpg',
        medium: 'https://randomuser.me/api/portraits/med/women/68.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/women/68.jpg',
      },
    },
    {
      gender: 'male',
      name: { title: 'Monsieur', first: 'Olivier', last: 'Joly' },
      email: 'olivier.joly@example.com',
      phone: '079 509 69 85',
      picture: {
        large: 'https://randomuser.me/api/portraits/men/39.jpg',
        medium: 'https://randomuser.me/api/portraits/med/men/39.jpg',
        thumbnail: 'https://randomuser.me/api/portraits/thumb/men/39.jpg',
      },
    },
  ],
  info: { seed: '268a2394d357f1ad', results: 50, page: 1, version: '1.4' },
};
